### ISSUE TITLE
Create allows you to create a resource that already exists

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#13]
I don't think you should be able to create a duplicate of a resource that is already there. This issue causes other problems for GET all and DELETE.

**Comment by lmr-99** [comment]
Fixed on the raiseEvents branch. To be tested on a single keyed API and committed to master.

**Comment by lmr-99** [comment]
Oh- also need to check if the error thrown should be a 500 or one of the 400 codes.

**Comment by ijhannig** [comment]
I'm having an error when I post something to my API, delete it, and then post something with the same name.  I think it's complaining because it wasn't actually deleted, it just had its active status set to no.  Anyone else having this error?

**Comment by lmr-99** [comment]
So right now the code checks to make sure it doesn't create a duplicate of a resource. (Graham just updated the code so it would just return a 201 without creating a duplicate, instead of throwing an error.) Delete just changes active status to "NO", so you should be able to do a PUT request instead to change the active status back to "YES".

**Comment by SpencerTuft** [comment]
Can we close this issue then?
