### ISSUE TITLE
DELETE deletes the first of a resource name, doesn't look at sort name

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#14]
If you delete something such as "Grad_Studies,ACT", it could potentially delete "Admissions,ACT" instead.

**Comment by lmr-99** [comment]
fixed on the raiseEvents branch. To be added to master.

**Comment by lmr-99** [comment]
To test on a single keyed API- works for double keyed

**Comment by SpencerTuft** [comment]
@lmr-99 Has this been resolved?

**Comment by lmr-99** [comment]
Yes I believe it has
