### ISSUE TITLE
links for info, modify and remove return the wrong links

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#3]
![screen shot 2017-10-09 at 4 39 57 pm](https://user-images.githubusercontent.com/23347776/31361628-61cab80a-ad11-11e7-8418-e63ae15ccd7a.png)

Should return the link "https://api.byu.edu/domains/identity/test_names/v1/Grad Studies,SAT
(needs to have the group as well as the name)

This is a problem for the GET / , GET /{},{} , and the GET /{},{}/logs functions

**Comment by SpencerTuft** [comment]
Fixed the links for apis with a sortName provided
