### ISSUE TITLE
POST / returns a link with undefined

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#4]
![screen shot 2017-10-09 at 4 41 33 pm](https://user-images.githubusercontent.com/23347776/31361825-96a07366-ad12-11e7-9b6d-ec87e9a0625e.png)
In the links for the POST /, it returns "https://api.byu.edu/domains/identity/test_names/v1/undefined" for the href when it should return something like "https://api.byu.edu/domains/identity/test_names/v1/{test_name},{test_type}

**Comment by SpencerTuft** [comment]
https://github.com/byu-oit/identity-code-api-controllers/issues/3
