### ISSUE TITLE
metadata for POST / should return a 201 response

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#5]
![screen shot 2017-10-09 at 4 49 39 pm](https://user-images.githubusercontent.com/23347776/31362012-85de9124-ad13-11e7-8b69-37052c314fa8.png)

In the metadata for the POST /, it should return a 201 response code instead of a 200 response code.

**Comment by SpencerTuft** [comment]
It done been blessed
