### ISSUE TITLE
GET /{},{} returns the first instance of test name, it doesn't match the type

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#6]
![screen shot 2017-10-09 at 4 49 39 pm](https://user-images.githubusercontent.com/23347776/31362183-6db24cfc-ad14-11e7-89d6-03edbed41f77.png)

The GET/{},{} appears to only return the first instance of the test_name; it doesn't seem to check to make sure that the test name and the test type match. It appears to be only checking for test name.

**Comment by SpencerTuft** [comment]
Fixed links in controller get_logs
