### ISSUE TITLE
logs return both Admission and Grad Studies

### ISSUE THREAD

**Issue by lmr-99** [byu-oit/identity-code-api-controllers#7]
<img width="836" alt="screen shot 2017-10-09 at 5 24 20 pm" src="https://user-images.githubusercontent.com/23347776/31362631-bc461d24-ad16-11e7-9b28-f5804c1788d3.png">

Should return just the log that matches both the test name and the test type. So, in this instance, it should only be returning the resource with the test_name ACT and the test_type Admission

**Comment by SpencerTuft** [comment]
https://github.com/byu-oit/identity-code-api-controllers/issues/3
